#!/bin/bash

set -e

echo "Building..."
docker-compose build

echo "Starting db..."
docker-compose up -d db
until docker-compose run db psql -h db -U postgres -c '\l' >/dev/null 2>&1; do
  echo "PostGIS is unavailable - sleeping"; sleep 1
done

echo "Generating a new APP_KEY..."
docker-compose run web python generate_key.py

echo "Creating tables..."
docker-compose run web python manage.py db init
docker-compose run web python manage.py db upgrade

echo "Compiling JS..."
docker-compose run yarn yarn install && \
  docker-compose run yarn yarn run build

docker-compose down
