#!/bin/bash

echo "Building..."
docker-compose build

echo "Generating a new APP_KEY..."
docker-compose run web python generate_key.py

echo "Creating tables..."
docker-compose run web python manage.py create_db

echo "Compiling JS..."
docker-compose run web npm install && \
  docker-compose run web npm run build
