"""empty message

Revision ID: 260a40ab34bc
Revises: 42aabd25b095
Create Date: 2018-05-09 02:18:22.914244

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '260a40ab34bc'
down_revision = '42aabd25b095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('dataset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'datasets', ['dataset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'dataset_id')
    # ### end Alembic commands ###
