"""empty message

Revision ID: 2ea95cb5f0ab
Revises: 260a40ab34bc
Create Date: 2018-09-05 06:15:23.965859

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ea95cb5f0ab'
down_revision = '260a40ab34bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idrs', sa.Column('profile', postgresql.JSON(
        astext_type=sa.Text()), nullable=True))
    op.add_column('polygons', sa.Column(
        'profile', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polygons', 'profile')
    op.drop_column('idrs', 'profile')
    # ### end Alembic commands ###
