"""empty message

Revision ID: 42aabd25b095
Revises: f59f060e0503
Create Date: 2018-05-09 01:13:46.439996

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '42aabd25b095'
down_revision = 'f59f060e0503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idrs', sa.Column('iteration', sa.Integer(), nullable=True))
    op.add_column('polygons', sa.Column('iteration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polygons', 'iteration')
    op.drop_column('idrs', 'iteration')
    # ### end Alembic commands ###
